version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=fyp_db
      - POSTGRES_USER=fyp_user
      - POSTGRES_PASSWORD=root
    ports:
      - "5433:5432"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      # If you have your satellite images in a different folder, mount it here:
      # - /path/to/your/images:/app/data
    environment:
      - DATABASE=postgres
      - DB_NAME=fyp_db
      - DB_USER=fyp_user
      - DB_PASSWORD=root
      - DB_HOST=db
      - DB_PORT=5432
      # Update this to match the path inside the container:
      - BASE_SATELLITE_IMAGE=/app/data/satellite_image.tif
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
