# Generated by Django 6.0.2 on 2026-02-18 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_id', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('analysis_type', models.CharField(choices=[('current', 'Current'), ('temporal', 'Temporal')], default='current', max_length=20)),
                ('coordinates', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Analysis histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
