# Generated by Django 6.0.4 on 2026-05-01 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_dashboard", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="analysishistory",
            name="summary",
            field=models.TextField(
                blank=True, default="", help_text="Short summary of the analysis result"
            ),
        ),
        migrations.AlterField(
            model_name="analysishistory",
            name="analysis_type",
            field=models.CharField(
                choices=[
                    ("current", "Current"),
                    ("temporal", "Temporal"),
                    ("upload", "Custom Upload"),
                ],
                default="current",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="UserPreferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "default_map_layer",
                    models.CharField(
                        choices=[
                            ("satellite", "Satellite View"),
                            ("street", "Street Map"),
                        ],
                        default="satellite",
                        max_length=20,
                    ),
                ),
                ("default_season", models.CharField(default="spring", max_length=20)),
                ("show_temperature_chart", models.BooleanField(default=True)),
                ("show_advanced_metrics", models.BooleanField(default=True)),
                ("notify_analysis_complete", models.BooleanField(default=True)),
                ("notify_weekly_digest", models.BooleanField(default=False)),
                (
                    "export_format",
                    models.CharField(
                        choices=[("pdf", "PDF"), ("png", "PNG")],
                        default="pdf",
                        max_length=10,
                    ),
                ),
                ("include_map_in_report", models.BooleanField(default=True)),
                ("include_charts_in_report", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
